name: PantryPilot Safe
version: "0.1.1"
slug: pantrypilot_safe
description: "Inventory add-on for Home Assistant with FastAPI backend."
url: "https://github.com/ConstableW/pantrypilot"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
host_network: true
options: {}
schema: {}