name: PantryPilot Safe
version: "0.1.1"
slug: pantrypilot_safe
description: A secure inventory management backend
arch:
  - aarch64
startup: services
boot: auto
ports:
  8010/tcp: 8010
image: ghcr.io/constablew/pantrypilot_safe_{arch}
build_from:
  aarch64: https://github.com/ConstableW/pantrypilot.git#main
