name: PantryPilot Safe
version: "0.1.1"
slug: pantrypilot_safe
description: Pantry management backend service
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: services
boot: auto
ports:
  8010/tcp: 8010
ingress: false
panel_icon: mdi:food
init: false
stage: experimental
hassio_role: default
hassio_api: true
homeassistant_api: true
host_network: false
environment:
  LOG_LEVEL: info
options: {}
schema: {}
image: ghcr.io/constablew/pantrypilot_safe/{arch}
